# Generated by Django 4.0 on 2022-04-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0004_profile2_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile2',
            new_name='Profile',
        ),
    ]
