# Generated by Django 4.0 on 2022-03-12 01:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_alter_articles_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='thumbnail',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
        migrations.AddField(
            model_name='articles',
            name='content_part1',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='content_part2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content_part3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content_part4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content_part5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content_part6',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnail/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnail/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnail/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnail/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnail/'),
        ),
    ]
