# Generated by Django 4.0 on 2022-03-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_thumbnail_articles_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user',
            new_name='author',
        ),
    ]
