# Generated by Django 4.0 on 2022-04-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articles_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='hashtag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.hashtag'),
            preserve_default=False,
        ),
    ]
