# Generated by Django 4.0 on 2022-04-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_hashtag_articles_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.hashtag'),
        ),
    ]
