# Generated by Django 4.0 on 2022-04-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_articles_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag',
            new_name='tagname2',
        ),
    ]
