# Generated by Django 4.0 on 2022-04-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_rename_hashtag_hashtag_tagname2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tagname2',
            new_name='tagname1',
        ),
    ]
