# Generated by Django 4.0 on 2022-02-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Blog',
        ),
    ]
